### PR TITLE
Add zoslib as a dependency

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**

### CODE REVIEW

**Review by MikeFultonDev — CHANGES_REQUESTED** [review]
is this a good time to add testing?

**Comment by IgorTodorovskiIBM** [comment]
> is this a good time to add testing?

Testing is enabled, all of the tests pass: https://github.com/ZOSOpenTools/xxhashport/blob/1ebb8567cd518015013222ae95b1ed45ab992cc0/buildenv#L35

**Review by MikeFultonDev — APPROVED** [review]
Great! The return 3 threw me.

**Comment by IgorTodorovskiIBM** [comment]
No longer needed as this was handled in another PR, closing

**Pull request closed without merging**
